apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 9191
      targetPort: {{ .Values.backendUser.containerPort }}
  type: ClusterIP
