# templates/service-redis.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
  type: ClusterIP
